### PR TITLE
ic_launcher.png improved

### PR DESCRIPTION
**Pull request by zumbrunnen**
While adressing https://github.com/DroidPlanner/3DRServices/issues/7 I noticed two things:

* I don't have a vectorized logo of Tower.
* The Tower icon is too flat compared to standard Android icons (see also: https://developer.android.com/design/style/iconography.html)

So, I created a SVG version (in Inkscape) and updated the `ic_launcher.png`s. It has a shadow below and a shadow dropping from the paper plane. Compare it to the "Downloads" icon on your handset and you'll spot the similarities.

comparison

If someone's intrested in the SVG version (or if this should be put under version control) - let me know.

If you think, Tower's icon (which is a paper plane... paper plane? tower? paper plane? :grin:) has to be flat, kindly refuse this PR.

### CODE REVIEW

**Comment by zumbrunnen** [comment]
WIP alert! :dragon_face: Please wait with processing this PR. I got more improvements.

**Comment by zumbrunnen** [comment]
OK, now it's ready for a review. :shipit: 

I've added customized status bar icons. They show the Tower icon better (instead of just a circle).

Further: When Tower is connected to the UAV, the notification icon's background changes to green.

Cross-check with https://github.com/DroidPlanner/3DRServices/pull/54

**Comment by ne0fhyk** [comment]
@zumbrunnen the updated Tower icon looks great as well!!

Could you put the svg version under version control as well. It should go in the [`Android/art`](https://github.com/DroidPlanner/droidplanner/tree/master/Android/art) directory.

thanks for the awesome work!

**Comment by zumbrunnen** [comment]
@ne0fhyk Done!

**Pull request merged**
